name = "MetidaBase"
uuid = "075456b7-4006-432f-9324-2f8453996c49"
authors = ["PharmCat <v.s.arnautov@yandex.ru> and contributors"]
version = "0.10.2"

[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"
CPUSummary = "2a0fbf3d-bb9c-48f3-b0a9-814d99fd7ab9"

[compat]
CategoricalArrays = "0.8, 0.9, 0.10"
DataFrames = "1"
Distributions = "0.20, 0.21, 0.22, 0.23, 0.24, 0.25"
StatsBase = "0.29, 0.30, 0.31, 0.32, 0.33"
StatsModels = "0.6"
Tables = "1"
PrettyTables = "2"
TypedTables = "1, 2"
CPUSummary = "0.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"

[targets]
test = ["Test", "CSV"]
